Repository dotnet/interactive, pull requests merged in 2022-07, with the labels that each got.

#2133 redirected console is reused in subsequent submissions for js
  src/microsoft-dotnet-interactive/src/consoleCapture.ts
  src/microsoft-dotnet-interactive/src/javascriptKernel.ts
  src/microsoft-dotnet-interactive/tests/javascriptKernel.test.ts
Labels: Area-JavaScript HTML CSS

#2134 Setup configuration for release notes
  .github/release.yml
Labels: Area-Build & Infrastructure

#2135 group by area
  .github/release.yml
Labels: Area-Build & Infrastructure

#2137 Improve NuGet package performance by using cache
  Directory.Build.targets
  src/Microsoft.DotNet.Interactive.FSharp/FSharpKernel.fs
  src/Microsoft.DotNet.Interactive.PackageManagement/PackageRestoreContext.cs
Labels: Area-Performance

#2139 Example extension that renders csharp code as sequence diagram
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.Interactive_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.ExtensionLab.Tests/DataFrameKernelExtensionTests.cs
  src/Microsoft.DotNet.Interactive.ExtensionLab.Tests/ExplainCodeExtensionTest.cs
  src/Microsoft.DotNet.Interactive.ExtensionLab.Tests/Microsoft.DotNet.Interactive.ExtensionLab.Tests.csproj
  src/Microsoft.DotNet.Interactive.ExtensionLab/ExplainCSharpCode.cs
  src/Microsoft.DotNet.Interactive.ExtensionLab/ExplainCodeExtension.cs
  src/Microsoft.DotNet.Interactive.ExtensionLab/InspectExtension.cs
  src/Microsoft.DotNet.Interactive.ExtensionLab/Inspector/CSharpCompiler/CSharpCompiler.cs
  src/Microsoft.DotNet.Interactive/KernelExtensions.cs
Labels: Area-Documentation

#2138 Added support for C4 diagrams in mermaid kernel
  src/Microsoft.DotNet.Interactive.Mermaid/MermaidMarkdownFormatter.cs
Labels: Area-Visualization, new feature

#2141 update packages
  Directory.Build.targets
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/Microsoft.DotNet.Interactive.ApiCompatibility.Tests.csproj
  src/Microsoft.DotNet.Interactive.AspNetCore.Tests/Microsoft.DotNet.Interactive.AspNetCore.Tests.csproj
  src/Microsoft.DotNet.Interactive.CSharpProject.Tests/Microsoft.DotNet.Interactive.CSharpProject.Tests.csproj
  src/Microsoft.DotNet.Interactive.Documents.Tests/Microsoft.DotNet.Interactive.Documents.Tests.csproj
  src/Microsoft.DotNet.Interactive.Documents/Microsoft.DotNet.Interactive.Documents.csproj
  src/Microsoft.DotNet.Interactive.ExtensionLab/Microsoft.DotNet.Interactive.ExtensionLab.csproj
  src/Microsoft.DotNet.Interactive.Formatting/Microsoft.DotNet.Interactive.Formatting.csproj
  src/Microsoft.DotNet.Interactive.Http/Microsoft.DotNet.Interactive.Http.csproj
  src/Microsoft.DotNet.Interactive.Jupyter.Tests/Microsoft.DotNet.Interactive.Jupyter.Tests.csproj
  src/Microsoft.DotNet.Interactive.Jupyter/Microsoft.DotNet.Interactive.Jupyter.csproj
  src/Microsoft.DotNet.Interactive.Kql.Tests/Microsoft.DotNet.Interactive.Kql.Tests.csproj
  src/Microsoft.DotNet.Interactive.Kql/Microsoft.DotNet.Interactive.Kql.csproj
  src/Microsoft.DotNet.Interactive.NetStandard20/Microsoft.DotNet.Interactive.Netstandard20.csproj
  src/Microsoft.DotNet.Interactive.SqlServer.Tests/Microsoft.DotNet.Interactive.SqlServer.Tests.csproj
  src/Microsoft.DotNet.Interactive.SqlServer/Microsoft.DotNet.Interactive.SqlServer.csproj
  src/Microsoft.DotNet.Interactive.Telemetry.Tests/Microsoft.DotNet.Interactive.Telemetry.Tests.csproj
  src/Microsoft.DotNet.Interactive.Telemetry/Microsoft.DotNet.Interactive.Telemetry.csproj
  src/Microsoft.DotNet.Interactive.Tests/Microsoft.DotNet.Interactive.Tests.csproj
  src/Microsoft.DotNet.Interactive/Microsoft.DotNet.Interactive.csproj
  src/dotnet-interactive.Tests/dotnet-interactive.Tests.csproj
  src/dotnet-interactive/dotnet-interactive.csproj
Labels: dependencies

#2162 skip encoding for image mimetypes
  src/dotnet-interactive-vscode-common/src/interactiveClient.ts
Labels: bug, Area-VS Code Extension, Area-Formatting

#2170 kernelInfo events updates the kernelInfo on proxies
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.Interactive_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.Tests/KernelInfoTests.cs
  src/Microsoft.DotNet.Interactive/CompositeKernel.cs
  src/Microsoft.DotNet.Interactive/Connection/ProxyKernel.cs
  src/Microsoft.DotNet.Interactive/Events/KernelInfoProduced.cs
  src/Microsoft.DotNet.Interactive/KernelHost.cs
  src/Microsoft.DotNet.Interactive/KernelInfo.cs
  src/microsoft-dotnet-interactive/src/compositeKernel.ts
  src/microsoft-dotnet-interactive/src/kernelHost.ts
  src/microsoft-dotnet-interactive/src/kernelInvocationContext.ts
  src/microsoft-dotnet-interactive/src/proxyKernel.ts
  src/microsoft-dotnet-interactive/tests/kernelHost.test.ts
  src/microsoft-dotnet-interactive/tests/kernelInfo.test.ts
  src/microsoft-dotnet-interactive/tests/proxykernel.test.ts
  src/microsoft-dotnet-interactive/tests/testSupport.ts
Labels: enhancement, Area-Messaging and Comms

#2176 make setters internal
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.Interactive_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive/KernelInfo.cs
Labels: Area-Build & Infrastructure

#2177 refactor kernel bootstrapper to enable testing
  src/microsoft-dotnet-interactive/src/webview/frontEndHost.ts
  src/microsoft-dotnet-interactive/src/webview/kernelApiBootstrapper.ts
  src/microsoft-dotnet-interactive/tests/frontEndHost.test.ts
Labels: Area-VS Code Extension
