Repository dotnet/interactive, pull requests merged in 2023-02, with the labels that each got.

#2668 special-case markdown in the dynamic grammar
  src/dotnet-interactive-vscode-common/src/dynamicGrammarSemanticTokenProvider.ts
  src/dotnet-interactive-vscode-common/tests/dynamicGrammarSemanticTokenProvider.test.ts
Labels: bug, Area-VS Code Extension

#2684 test fallback to text/plain
  src/Microsoft.DotNet.Interactive.Tests/KeyValueStoreKernelTests.cs
Labels: Area-Variable sharing

#2687 disable docker build
  azure-pipelines.yml
Labels: Area-Build & Infrastructure

#2688 delete my binder
  Dockerfile
  README.md
  docs/CreateBinder.md
  docs/NotebooksOnBinder.md
  docs/NotebookswithJupyter.md
  dotnet-interactive.sln
  samples/my binder/Dockerfile
  samples/my binder/notebooks/README.md
  samples/notebooks/fsharp/Samples/DataFrame-Getting-Started.ipynb
  samples/notebooks/polyglot/COVID-19-fsharp.dib
  samples/notebooks/polyglot/COVID-19.ipynb
  samples/notebooks/polyglot/d3js.ipynb
  samples/readme.md
Labels: Area-Documentation

#2690 Value explorer improvements
  src/dotnet-interactive-vscode-common/src/variableExplorer.ts
  src/polyglot-notebooks-ui-components/src/components/VariableGrid.tsx
Labels: Area-VS Code Extension

#2692 if .ipynb document metadata isn't present, fall back to interpreting the kernelspec
  src/dotnet-interactive-vscode-common/src/metadataUtilities.ts
  src/dotnet-interactive-vscode-common/src/notebookCellStatusBarItemProvider.ts
  src/dotnet-interactive-vscode-common/tests/metadataUtilities.test.ts
  src/dotnet-interactive-vscode-insiders/src/notebookControllers.ts
Labels: bug, Area-VS Code Extension

#2706 fix build definition
  azure-pipelines.yml
Labels: Area-Build & Infrastructure

#2709 improve column resize
  src/polyglot-notebooks-ui-components/src/components/VariableGrid.tsx
Labels: bug

#2716 kernelinfo carries information on kernel type
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.Interactive_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.Tests/Connection/SerializationTests.Event_contract_has_not_been_broken.approved.KernelInfoProduced.json
  src/Microsoft.DotNet.Interactive/CompositeKernel.cs
  src/Microsoft.DotNet.Interactive/Connection/ProxyKernel.cs
  src/Microsoft.DotNet.Interactive/KernelInfo.cs
  src/polyglot-notebooks-vscode-common/src/dynamicGrammarSemanticTokenProvider.ts
  src/polyglot-notebooks-vscode-common/src/kernelSelectorUtilities.ts
  src/polyglot-notebooks-vscode-common/src/metadataUtilities.ts
  src/polyglot-notebooks-vscode-common/tests/dynamicGrammarSemanticTokenProvider.test.ts
  src/polyglot-notebooks-vscode-common/tests/metadataUtilities.test.ts
  src/polyglot-notebooks/src/compositeKernel.ts
  src/polyglot-notebooks/src/connection.ts
  src/polyglot-notebooks/src/contracts.ts
  src/polyglot-notebooks/src/kernel.ts
  src/polyglot-notebooks/src/proxyKernel.ts
  src/polyglot-notebooks/tests/frontEndHost.test.ts
  src/polyglot-notebooks/tests/kernelHost.test.ts
  src/polyglot-notebooks/tests/kernelInfo.test.ts
  src/polyglot-notebooks/tests/proxykernel.test.ts
Labels: Area-Messaging and Comms

#2734 fix package import
  samples/notebooks/journey/showcaseteacher.dib
Labels: Area-Documentation

#2740 #!set honours the mimetype and ignores reference
  src/Microsoft.DotNet.Interactive.Tests/KeyValueStoreKernelTests.cs
  src/Microsoft.DotNet.Interactive.Tests/SetMagicCommandTests.cs
  src/Microsoft.DotNet.Interactive.Tests/VariableSharingTests.cs
  src/Microsoft.DotNet.Interactive/KeyValueStoreKernel.cs
  src/Microsoft.DotNet.Interactive/Parsing/SubmissionParser.cs
Labels: Area-Variable sharing

#2743 Cancel commands when split
  src/Microsoft.DotNet.Interactive.Tests/CancelCommandTests.cs
  src/Microsoft.DotNet.Interactive.Tests/SetMagicCommandTests.cs
  src/Microsoft.DotNet.Interactive/KernelInvocationContext.cs
Labels: bug, Area-Messaging / scheduling / comms

#2746 use set command in github notebook
  samples/notebooks/polyglot/github repo milestone report.ipynb
Labels: Area-Documentation

#2747 report all errors when generating dynamic semantic tokens
  src/polyglot-notebooks-vscode-common/src/documentSemanticTokenProvider.ts
Labels: Area-Build & Infrastructure

#2749 fix css for value grid
  src/polyglot-notebooks-ui-components/src/components/VariableGrid.tsx
  src/polyglot-notebooks-ui-components/src/style.css
Labels: bug, Area-VS Code Extension

#2745 improve kql and sql connection experience
  src/Microsoft.DotNet.Interactive.Kql.Tests/KqlConnectionTests.cs
  src/Microsoft.DotNet.Interactive.Kql/ConnectKqlCommand.cs
  src/Microsoft.DotNet.Interactive.SqlServer.Tests/MsSqlConnectionTests.cs
  src/Microsoft.DotNet.Interactive.SqlServer/ConnectMsSqlCommand.cs
Labels: bug, Area-SQL / data querying

#2712 allow persisting default values for new notebooks
  src/polyglot-notebooks-vscode-common/src/commands.ts
  src/polyglot-notebooks-vscode-insiders/package.json
  src/polyglot-notebooks-vscode/package.json
Labels: enhancement, Area-VS Code Extension

#2763 cancelling doesn't leak infos
  src/Microsoft.DotNet.Interactive/KernelInvocationContext.cs
Labels: Area-Polyglot Notebooks Extension

#2771 value kernel honours content type in --from-url
  src/Microsoft.DotNet.Interactive.Tests/KeyValueStoreKernelTests.cs
  src/Microsoft.DotNet.Interactive/KeyValueStoreKernel.cs
Labels: Area-Variable sharing
