Repository dotnet/interactive, pull requests merged in 2023-05, with the labels that each got.

#2960 handle multiple #!set commands in sungle submission
  src/Microsoft.DotNet.Interactive.Tests/VariableSharingTests.SetMagicCommand.cs
  src/Microsoft.DotNet.Interactive/KernelExtensions.cs
Labels: bug, Area-Variable sharing

#2968 clear problem window for closed notebooks
  src/polyglot-notebooks-vscode-common/src/activeNotebookTracker.ts
Labels: bug, Area-Polyglot Notebooks Extension

#2962 port localization to stable
  src/polyglot-notebooks-vscode-insiders/package.json
  src/polyglot-notebooks-vscode/do-version-upgrade.ps1
  src/polyglot-notebooks-vscode/l10n/bundle.l10n.json
  src/polyglot-notebooks-vscode/package-lock.json
  src/polyglot-notebooks-vscode/package.json
  src/polyglot-notebooks-vscode/package.nls.cs.json
  src/polyglot-notebooks-vscode/package.nls.de.json
  src/polyglot-notebooks-vscode/package.nls.es.json
  src/polyglot-notebooks-vscode/package.nls.fr.json
  src/polyglot-notebooks-vscode/package.nls.it.json
  src/polyglot-notebooks-vscode/package.nls.ja.json
  src/polyglot-notebooks-vscode/package.nls.json
  src/polyglot-notebooks-vscode/package.nls.ko.json
  src/polyglot-notebooks-vscode/package.nls.pl.json
  src/polyglot-notebooks-vscode/package.nls.pt-BR.json
  src/polyglot-notebooks-vscode/package.nls.ru.json
  src/polyglot-notebooks-vscode/package.nls.tr.json
  src/polyglot-notebooks-vscode/package.nls.zh-Hans.json
  src/polyglot-notebooks-vscode/package.nls.zh-Hant.json
Labels: Area-Localization and Globalization

#2986 upgrade to RX 6
  Directory.Build.props
  src/Microsoft.DotNet.Interactive.CSharpProject.Tests/Microsoft.DotNet.Interactive.CSharpProject.Tests.csproj
  src/Microsoft.DotNet.Interactive.CSharpProject/Microsoft.DotNet.Interactive.CSharpProject.csproj
  src/dotnet-interactive.Tests/dotnet-interactive.Tests.v3.ncrunchproject
Labels: Area-Build & Infrastructure

#2988 revert RX to 5.0.0
  Directory.Build.props
Labels: Area-Build & Infrastructure

#2995 Fix issues with stored SQL or KQL queries not showing in variable explorer
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.kql_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.mssql_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.Kql.Tests/KqlConnectionTests.cs
  src/Microsoft.DotNet.Interactive.Kql.Tests/Microsoft.DotNet.Interactive.Kql.Tests.v3.ncrunchproject
  src/Microsoft.DotNet.Interactive.Kql/MsKqlKernel.cs
  src/Microsoft.DotNet.Interactive.SqlServer.Tests/Microsoft.DotNet.Interactive.SqlServer.Tests.v3.ncrunchproject
  src/Microsoft.DotNet.Interactive.SqlServer.Tests/MsSqlConnectionTests.cs
  src/Microsoft.DotNet.Interactive.SqlServer/MsSqlKernel.cs
  src/Microsoft.DotNet.Interactive.SqlServer/ToolsServiceKernel.cs
Labels: Area-Variable sharing

#3002 Avoid sending redundant empty DiagnosticsProduced events.
  src/Microsoft.DotNet.Interactive.CSharp/CSharpKernel.cs
  src/Microsoft.DotNet.Interactive.CSharpProject/CSharpProjectKernel.cs
  src/Microsoft.DotNet.Interactive.HttpRequest/HttpRequestKernel.cs
  src/Microsoft.DotNet.Interactive.PowerShell.Tests/PowerShellKernelTests.cs
  src/Microsoft.DotNet.Interactive.PowerShell/PowerShellKernel.cs
Labels: Area-Messaging / scheduling / comms

#3004 Delete the Microsoft.DotNet.Interactive.Shared project.
  dotnet-interactive.sln
  src/Microsoft.DotNet.Interactive.Documents/Microsoft.DotNet.Interactive.Documents.csproj
  src/Microsoft.DotNet.Interactive.Formatting/Microsoft.DotNet.Interactive.Formatting.csproj
  src/Microsoft.DotNet.Interactive/Microsoft.DotNet.Interactive.csproj
  src/Microsoft.DotNet.Interactive/Utility/DictionaryExtensions.cs
  src/Microsoft.DotNet.Interactive/Utility/IOExtensions.cs
  src/Microsoft.DotNet.Interactive/Utility/NullableAttributes.cs
  src/Microsoft.DotNet.Interactive/Utility/Range.cs
  src/Microsoft.Dotnet.Interactive.Shared/Microsoft.Dotnet.Interactive.Shared.projitems
  src/Microsoft.Dotnet.Interactive.Shared/Microsoft.Dotnet.Interactive.Shared.shproj
Labels: Area-Build & Infrastructure

#3003 Remove DiagnosticLogEntryProduced event.
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.Interactive_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.Jupyter/ExecuteRequestHandler.cs
  src/Microsoft.DotNet.Interactive.Tests/Connection/SerializationTests.Event_contract_has_not_been_broken.approved.DiagnosticLogEntryProduced.json
  src/Microsoft.DotNet.Interactive.Tests/Connection/SerializationTests.cs
  src/Microsoft.DotNet.Interactive/Connection/KernelCommandAndEventReceiver.cs
  src/Microsoft.DotNet.Interactive/Connection/KernelEventEnvelope.cs
  src/Microsoft.DotNet.Interactive/Events/DiagnosticLogEntryProduced.cs
  src/Microsoft.DotNet.Interactive/Events/KernelEventExtensions.cs
  src/polyglot-notebooks-vscode-common/src/stdioDotnetInteractiveChannel.ts
  src/polyglot-notebooks/src/contracts.ts
Labels: Area-Messaging / scheduling / comms
