Repository dotnet/interactive, pull requests merged in 2023-06, with the labels that each got.

#3007 stable release
  src/polyglot-notebooks-vscode-insiders/package.json
  src/polyglot-notebooks-vscode-insiders/src/vscode.d.ts
  src/polyglot-notebooks-vscode/package.json
  src/polyglot-notebooks-vscode/src/vscode.d.ts
Labels: Area-Build & Infrastructure

#3015 add ipynb file for local testing
  NotebookTestScript.ipynb
Labels: Area-Documentation

#3036 Fix issue with input gesture not working
  src/Microsoft.DotNet.Interactive/KernelExtensions.cs
Labels: bug, Area-Variable sharing

#3037 fix tool
  src/polyglot-notebooks-vscode-insiders/package.json
  src/polyglot-notebooks-vscode/package.json
Labels: Area-Build & Infrastructure

#3038 allow TypeFormatterSource attributes to set MIME type preferences
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.Formatting_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.Formatting.Tests/FormatterTests.FormatterSources.cs
  src/Microsoft.DotNet.Interactive.Formatting/Formatter.cs
  src/Microsoft.DotNet.Interactive.Formatting/TypeFormatterSourceAttribute.cs
  src/Microsoft.DotNet.Interactive/Kernel.cs
  src/Microsoft.DotNet.Interactive/Utility/StringExtensions.cs
  src/dotnet-interactive/Pocket/Format.CustomizeLogString.cs
Labels: enhancement, Area-Formatting

#3050 Update setup-raspbian.sh
  tools/setup-raspbian.sh
Labels: Area-Build & Infrastructure
