Repository dotnet/interactive, pull requests merged in 2023-11, with the labels that each got.

#3292 #import bug
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.Interactive_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.Tests/ImportNotebookTests.cs
  src/Microsoft.DotNet.Interactive/KernelExtensions.cs
  src/Microsoft.DotNet.Interactive/KernelInvocationContext.cs
  src/dotnet-interactive/PackageDirectoryExtensionLoader.cs
Labels: bug

#3296 removed DotNet-Blob-Feed groups
  azure-pipelines.yml
  eng/common/templates/post-build/common-variables.yml
Labels: Area-Build & Infrastructure

#3303 fix_script
  src/Microsoft.DotNet.Interactive.AIUtilities/extension.dib
Labels: Area-Build & Infrastructure

#3305 address comment to remove BlobFeed override
  azure-pipelines.yml
Labels: Area-Build & Infrastructure

#3312 fix build
  azure-pipelines.yml
Labels: Area-Build & Infrastructure

#3318 update packages
  src/Microsoft.DotNet.Interactive.SqlServer/Microsoft.DotNet.Interactive.SqlServer.csproj
Labels: Area-Build & Infrastructure

#3320 update_sdk
  src/polyglot-notebooks-vscode-insiders/package.json
  src/polyglot-notebooks-vscode/package.json
Labels: Area-Build & Infrastructure

#3321 remove package
  src/Microsoft.DotNet.Interactive.AIUtilities.Tests/Microsoft.DotNet.Interactive.AIUtilities.Tests.csproj
  src/Microsoft.DotNet.Interactive.AIUtilities/CosineSimilarityComparer.cs
  src/Microsoft.DotNet.Interactive.AIUtilities/GptFunction.cs
  src/Microsoft.DotNet.Interactive.AIUtilities/Microsoft.DotNet.Interactive.AIUtilities.csproj
  src/Microsoft.DotNet.Interactive.AIUtilities/Sampling.cs
  src/Microsoft.DotNet.Interactive.AIUtilities/Text.cs
  src/Microsoft.DotNet.Interactive.AIUtilities/Tokenizer.cs
  src/Microsoft.DotNet.Interactive.AIUtilities/Vectors.cs
Labels: Area-Build & Infrastructure

#3325 update fsharp core and compiler service
  Directory.Build.targets
  src/Microsoft.DotNet.Interactive.FSharp/FsAutoComplete/Lexer.fs
Labels: Area-Build & Infrastructure

#3330 update ai notebooks
  samples/notebooks/ai/AI prompt playground.ipynb
  samples/notebooks/ai/Ai skills experiments.ipynb
  samples/notebooks/ai/Audio processing.ipynb
  samples/notebooks/ai/Chat Agent.ipynb
  samples/notebooks/ai/E2E.ipynb
  samples/notebooks/ai/Explain code using Mermaid diagram.ipynb
  samples/notebooks/ai/Explain code using mermaid kernel and LLM.ipynb
  samples/notebooks/ai/Getting started.ipynb
  samples/notebooks/ai/Knowledge kernel.ipynb
  samples/notebooks/ai/end to end.ipynb
  samples/notebooks/ai/image generation.ipynb
Labels: Area-Documentation

#3337 Add Microsoft.DotNet.Interactive.Browser.Tests to test retry list
  test-retry-runner.ps1
Labels: Area-Build & Infrastructure

#3338 Enable C#12
  src/Microsoft.DotNet.Interactive.CSharp/CSharpKernel.cs
Labels: enhancement, Area-C#

#3342 Fixed tpyos, added some instructions, and fixed an AI example.
  samples/notebooks/ai/AI prompt playground.ipynb
  samples/notebooks/ai/Audio processing.ipynb
  samples/notebooks/ai/Chat Agent.ipynb
  samples/notebooks/ai/E2E.ipynb
  samples/notebooks/ai/Knowledge kernel.ipynb
Labels: Area-Documentation

#3344 A few miscellaneous docs updates
  docs/NotebookswithJupyter.md
  docs/README.md
  docs/adding-jupyter-kernels.md
  samples/notebooks/csharp/Docs/Formatting-outputs.ipynb
  samples/notebooks/csharp/Samples/interactive-metrics.ipynb
  src/Microsoft.DotNet.Interactive.Jupyter/Http/HttpApiClient.cs
  src/polyglot-notebooks-vscode-insiders/README.md
  src/polyglot-notebooks-vscode/README.md
  tools/setup-raspbian.sh
Labels: Area-Documentation

#3345 Check for embedded expressions in Url Node
  src/Microsoft.DotNet.Interactive.Http.Parsing/Parsing/HttpRequestParser.cs
  src/Microsoft.DotNet.Interactive.Http.Tests/HttpKernelTests.cs
Labels: Area-HTTP

#3347 update packages
  Directory.Build.props
Labels: Area-Build & Infrastructure

#3246 Multi-target Microsoft.DotNet.Interactive.csproj to support both netstandard2.0 as well as net8.0
  dotnet-interactive.sln
  src/Microsoft.DotNet.Interactive.ApiCompatibility.Tests/ApiCompatibilityTests.Interactive_api_is_not_changed.approved.txt
  src/Microsoft.DotNet.Interactive.Browser/Microsoft.DotNet.Interactive.Browser.csproj
  src/Microsoft.DotNet.Interactive.NetFramework.Tests/(Pocket)/Logger/LogEvents.cs
  src/Microsoft.DotNet.Interactive.NetFramework.Tests/Directory.Build.props
  src/Microsoft.DotNet.Interactive.NetFramework.Tests/Microsoft.DotNet.Interactive.NetFramework.Tests.csproj
  src/Microsoft.DotNet.Interactive.NetFramework.Tests/Microsoft.DotNet.Interactive.NetFramework.Tests.v3.ncrunchproject
  src/Microsoft.DotNet.Interactive.Tests/StdIoKernelConnectorTests.cs
  src/Microsoft.DotNet.Interactive.VisualStudio/Directory.Build.props
  src/Microsoft.DotNet.Interactive.VisualStudio/Microsoft.DotNet.Interactive.Netstandard20.v3.ncrunchproject
  src/Microsoft.DotNet.Interactive.VisualStudio/Microsoft.DotNet.Interactive.VisualStudio.csproj
  src/Microsoft.DotNet.Interactive/Connection/StdIoKernelConnector.cs
  src/Microsoft.DotNet.Interactive/Microsoft.DotNet.Interactive.csproj
  test-retry-runner.ps1
Labels: Area-API
