Repository dotnet/interactive, pull requests merged in 2023-12, with the labels that each got.

#3366 update extension messages for sdk install
  src/polyglot-notebooks-vscode-common/src/extension.ts
  src/polyglot-notebooks-vscode-insiders/help/DotNetVersion.md
  src/polyglot-notebooks-vscode/help/DotNetVersion.md
Labels: Area-Polyglot Notebooks Extension

#3367 fix dotnet download url
  src/polyglot-notebooks-vscode-common/src/extension.ts
  src/polyglot-notebooks-vscode-insiders/help/DotNetVersion.md
  src/polyglot-notebooks-vscode/help/DotNetVersion.md
Labels: Area-Build & Infrastructure

#3360 Fix input prompt quoting issue
  src/Microsoft.DotNet.Interactive.PowerShell.Tests/Microsoft.DotNet.Interactive.PowerShell.Tests.v3.ncrunchproject
  src/Microsoft.DotNet.Interactive.PowerShell/PowerShellKernel.cs
  src/Microsoft.DotNet.Interactive.Tests/InputsWithinMagicCommandsTests.cs
  src/Microsoft.DotNet.Interactive.Tests/Microsoft.DotNet.Interactive.Tests.v3.ncrunchproject
  src/Microsoft.DotNet.Interactive.Tests/VariableSharingTests.SetMagicCommand.cs
  src/Microsoft.DotNet.Interactive/KernelExtensions.cs
  src/Microsoft.DotNet.Interactive/KernelScheduler.cs
  src/Microsoft.DotNet.Interactive/Parsing/SubmissionParser.cs
  src/Microsoft.DotNet.Interactive/PasswordString.cs
  src/dotnet-interactive/KernelExtensionLoader.cs
Labels: Area-Variable sharing

#3358 Update magic-commands.md with #!set
  docs/magic-commands.md
Labels: Area-Documentation

#3369 update ai pacakge
  samples/notebooks/ai/AI prompt playground.ipynb
  samples/notebooks/ai/Audio processing.ipynb
  samples/notebooks/ai/Chat Agent.ipynb
  samples/notebooks/ai/E2E.ipynb
  samples/notebooks/ai/Explain code using Mermaid diagram.ipynb
  samples/notebooks/ai/Getting started.ipynb
  samples/notebooks/ai/Knowledge kernel.ipynb
  samples/notebooks/ai/image generation.ipynb
Labels: Area-Documentation

#3388 Update MANUAL-TESTING.md
  MANUAL-TESTING.md
Labels: Area-Documentation
