Repository dotnet/interactive, pull requests merged in 2023-03, with the labels that each got.

#2785 simplify code types
  .github/release.yml
  src/Microsoft.DotNet.Interactive.CSharp/CSharpKernel.cs
  src/Microsoft.DotNet.Interactive.ExtensionLab/SQLiteKernel.cs
  src/Microsoft.DotNet.Interactive.FSharp/FSharpKernel.fs
  src/Microsoft.DotNet.Interactive.HttpRequest/HttpRequestKernel.cs
  src/Microsoft.DotNet.Interactive.Kql/MsKqlKernel.cs
  src/Microsoft.DotNet.Interactive.Mermaid/MermaidKernel.cs
  src/Microsoft.DotNet.Interactive.PowerShell/PowerShellKernel.cs
  src/Microsoft.DotNet.Interactive.SqlServer/MsSqlKernel.cs
  src/Microsoft.DotNet.Interactive/KeyValueStoreKernel.cs
  src/polyglot-notebooks-vscode-common/src/kernelSelectorUtilities.ts
  src/polyglot-notebooks-vscode-common/tests/kernelSelectorUtilities.test.ts
  src/polyglot-notebooks/src/javascriptKernel.ts
  src/polyglot-notebooks/tests/frontEndHost.test.ts
  src/polyglot-notebooks/tests/kernelInfo.test.ts
Labels: Area-Polyglot Notebooks Extension

#2788 Release 1.76
  src/Microsoft.DotNet.Interactive.Tests/ProxyKernelConnectionTestsBase.cs
  src/Microsoft.DotNet.Interactive/Connection/KernelCommandEnvelope.cs
  src/Microsoft.DotNet.Interactive/KqlDiscoverabilityKernel.cs
  src/Microsoft.DotNet.Interactive/SqlDiscoverabilityKernel.cs
  src/polyglot-notebooks-vscode-insiders/package.json
  src/polyglot-notebooks-vscode-insiders/src/vscode.d.ts
  src/polyglot-notebooks-vscode-insiders/tools/buildSemanticTokenScopes.js
  src/polyglot-notebooks-vscode/do-version-upgrade.ps1
  src/polyglot-notebooks-vscode/package.json
  src/polyglot-notebooks-vscode/src/vscode.d.ts
  src/polyglot-notebooks-vscode/update-api.ps1
Labels: Area-Build & Infrastructure

#2814 restrict webview communication to the specific notebook
  src/polyglot-notebooks-vscode-common/src/notebookControllers.ts
  src/polyglot-notebooks/src/webview/activation.ts
Labels: Area-Messaging / scheduling / comms

#2815 throttle commands at the kernel host level
  src/polyglot-notebooks/src/kernelHost.ts
Labels: Area-Messaging / scheduling / comms

#2818 remove outdated d3js sample
  samples/notebooks/polyglot/d3js.ipynb
  samples/notebooks/polyglot/polyglot telemetry.dib
Labels: Area-Documentation

#2826 revert queue for command handling in kernelhost
  samples/notebooks/polyglot/d3js widget.ipynb
  src/polyglot-notebooks/src/kernelHost.ts
Labels: Area-JavaScript HTML CSS

#2829 disable csharp project tests
  test-retry-runner.ps1
Labels: Area-Build & Infrastructure

#2830 ensure requestInput and sendEditableCode are sequencial
  src/polyglot-notebooks/src/kernelHost.ts
  src/polyglot-notebooks/src/kernelScheduler.ts
Labels: Area-Messaging / scheduling / comms

#2845 lock tool
  src/polyglot-notebooks-vscode-insiders/package.json
  src/polyglot-notebooks-vscode/UPDATING-TO-NEW-VERSION-OF-STABLE.md
  src/polyglot-notebooks-vscode/package.json
Labels: Area-Build & Infrastructure

#2846 update webpack
  src/polyglot-notebooks-ui-components/package-lock.json
  src/polyglot-notebooks-ui-components/package.json
Labels: Area-Build & Infrastructure

#2844 upgrade Code Analysis to 4.5.0
  Directory.Build.props
  src/Microsoft.DotNet.Interactive.CSharp/CompletionExtensions.cs
  src/Microsoft.DotNet.Interactive.CSharpProject/Packaging/FileTextLoader.cs
Labels: Area-Build & Infrastructure

#2857 strip cell metadata for markdown cells
  src/polyglot-notebooks-vscode-common/src/commands.ts
  src/polyglot-notebooks-vscode-common/src/notebookControllers.ts
Labels: Area-Polyglot Notebooks Extension

#2860 locked_version
  src/polyglot-notebooks-vscode/package.json
Labels: Area-Build & Infrastructure

#2866 Improve memory usage
  src/Microsoft.DotNet.Interactive.CSharp/InteractiveWorkspace.cs
Labels: Area-C#, Area-Performance
