Repository dotnet/interactive, pull requests merged in 2024-02, with the labels that each got.

#3435 when a variable cannot be formatted prevents value infos to work
  src/polyglot-notebooks-vscode-common/src/languageServices/hover.ts
  src/polyglot-notebooks/src/javascriptKernel.ts
Labels: bug, Area-Variable sharing

#3443 upgrade pacakges
  src/Microsoft.DotNet.Interactive.SqlServer/ConnectMsSqlCommand.cs
  src/Microsoft.DotNet.Interactive.SqlServer/Microsoft.DotNet.Interactive.SqlServer.csproj
Labels: Area-Build & Infrastructure

#3442 Improve a couple of http kernel error messages
  src/Microsoft.DotNet.Interactive.Http.Parsing/Parsing/HttpDiagnostics.cs
  src/Microsoft.DotNet.Interactive.Http.Tests/HttpKernelTests.cs
Labels: Area-HTTP

#3454 add logging to grammar token
  src/polyglot-notebooks-vscode-common/src/documentSemanticTokenProvider.ts
Labels: Area-Build & Infrastructure

#3472 obfuscate pwd in sql and kql kernel display events
  src/Microsoft.DotNet.Interactive.SqlServer/MsSqlKernel.cs
  src/Microsoft.DotNet.Interactive.SqlServer/ToolsServiceKernel.cs
Labels: Area-SQL / data querying
